# Setup
title: 코드를 빵빵하게
description: 초보 개발자의 블로그입니다.
url: https://github.com/La-Mancha93
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: La-Mancha93
  card: summary
logo: logo.png
social:
  name: SS Kim
  links:
    - https://github.com/La-Mancha93
google_site_verification: xxxxx
lang: ko

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: SS Kim
  url: https://github.com/La-Mancha93
  email: sskim@secuwow.com
